### PR TITLE
Removed bacon and added brunch

### PR DESCRIPTION
**Pull request by vbajs**
I removed bacon for the noobs who may think they are building for their device then ending up building for bacon (it might happen)
And I added brunch as it works and builds for most of the devices

### CODE REVIEW

**Comment by MZO9400** [comment]
Hahaha lol. Nice catch tho.

**Comment by MZO9400** [comment]
But the mka stays bacon as this is not device specific.

**Comment by vbajs** [comment]
Then why mka is here while its only for bacon?

**Comment by MZO9400** [comment]
It is how the command is 

mka bacon = make are same commands.

**Comment by vbajs** [comment]
Wait, I am confused now
If I made a mka bacon jfltexx (for example), will it build bacon or jfltexx?

**Comment by r-matlock** [comment]
I will clarify what make bacon and mka bacon do and add brunch to the README. Thanks for the idea.

**Pull request closed without merging**
